travis:
  secure:
    BINSTAR_TOKEN: mvO4sG7wubq/SloE4m1cQqjhFzOu5xBMA5BG8TuoPUh2ywGQWMnlJd2nuKxHQZXE98Ug2Tg4nPzLppRL5o9RDom2Dg7U/SAurjfTZRzrgjpH+858B9sYPkhJIzIgdEcnCaBndaI7W0XUDwRRkenS4mj/lAgbGNjo0dVLw+euGrSvEIhEoMkd4ZAX0lvhYpEyyXo6Q2FamPr4YoJ0ssmSX7npLdlD7qIFK7KLwik7jA6OpjSOTK+muUqkkGKnWiqZpMJhBpfspnAIVbIII680Y+N+Cq9y59S+MBqNsoFU77huw5AUf+dkI/0JR8PEJU5bGbtD1nMg0BIcCRxEIWZiKOkkq5v7PE3h18Yu9lM/3uihmiN/DfYMfh9bSEEOqMk72E8Vh9ZsmkESby4P9cxGSi7raT+m9HiP78H9tS7DgujQoNeXa8xt3fwgilcpMiNG9w38FlAJjUv4DrU6l8XZCIELP6IimCcHa+UDbtwI64piDNmfxhK4UYB9Sl1otl3v6AkhzHc2SIcaEOBI4nUZO14BCZmcuDVdDSkGkdX9mWLBOpxTn0x6kl0ei/S+iBcXoMOgdx4t6IlvOIugare3qV4P4u85lkWkE1gU09z2iOxiBcI7Jz1PglXs1OBnPvJ65ytSdh9oVzKPkgGcD5Rn7TFk1TdsOcamIii97q9bfCk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
