travis:
  secure:
    BINSTAR_TOKEN: mso9/LBdDSz49OzCuYdwzybp92lxVGMgcuGR/pulC+q9TlWYSxm92RAD3n+Sp7uco2STCeOwTZ4tG7rh8yIRMe7OPbflHVPdtrGlyJeBlYFPE3tbjhhoSBDB0VnN1Jk5zFyyV9/uEDYv1iMWEAqjzmTTESaJbXml2dybzMwOJj9TQvKCjQOJa7n6CnQapGSbHAgiF9M53nPNyoj0vwo4m52t45N6m6PQOtNvfli301MXhp6CGba7ftcruiXhYcCIJn7GmajBNwaMPSxU05kH9GLsK0nk06W3LoGkmUQwF1ofGev7sMmWHVkk/0Gle5xLgEO/1189q+XCq5qGT2k48CAz7BCDF4dPP0Da9yI/k2SAVhAzESYskHjzPLPqDcQ4fF3o+zyCfBG6c6WGZLAwnXqlOywRy5BKHsoWKdeFpkxL8MIxgD/D8ImRjxmzKHnDr/2+q7lvTtr/1FkYd2SwXhFeAzhneuTXWjeR5iSnnYMfyeQa8L5xl8IVmlm80ujnU+u5NotC1GSAa7R0XawpgE4Wv4nJxIhsePLVPafU75basmN8dW2bxTCLHx7KfJq1W3XN9oMe0ddYAjRR5qZ6gE+4rFyy7fhIih9RkLMKwKe/ykvjSnP1mD6PoJhbMNiy8VEtg5dNMY1o+RmZ3gZX01KU8XHxpvtLz5w56EM56XA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
