travis:
  secure:
    BINSTAR_TOKEN: nRp+f13jjxe/SzIvy/8oHR3HfbqXBMioztHel4glFaAaVbeZND6nO69Mmih3nAOcF/h2OIqRvI5SfwL4Jy6UQWOaN6XVhtV9twraCX+p613AGI3P3uKRqV+fzonw8WD5fHlikj4ED6H/irQeUGLlJsvMCJ906105Vxlf8O7RfsPhiahOOMXCboGG/hAMnRuTZ1L0CYzL2ay//c8VHOi6rC0USFmiTaUolOt0hNthsMz0wde8rgO0wLH8gQUmyIY/YSCSENUi8NydG7YTi6Smg/Cp+adaBJ3/+sIeplEpJQPvVYg6Q+o55W55KOdei+hu1vOU+SyhxeMdcFzVXtHlv7nhPmARgpYGwdNpG50ELPaug3QdlLAH2StVj3XNNIoLeKUh6bIGKuykbVMhLj0xluTp/c4dIcbjY1a3t8uzNeoIueZjlUzX9BhWBuoRTFSjsI+Y9Sg2j3RQfh0cyY9wCnaZ/YUFGgVXsvFzCgQL7wRD1X/ytLkKjhyE/HdjfZQS1kSrDBc3ycJnXMP2fARYQaGyOrWxgEUuIb0SRHLhv0gTRqe0fAlkYLy9lw0Nnv9hK0CFECyv9JBnH+txxt0IlK3BdZhECaImix3xjc5l9Hiot7aTwQxRbJjhHhMXkuPIscXsySdMSjfb/rB7HYMcfWkNKDPdBzAdWkrB7VYWY0g=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
